---
- name: Set Password Expiration Days
  lineinfile:
    dest: '/etc/login.defs'
    regexp: "PASS_MAX_DAYS"
    line: "PASS_MAX_DAYS 365"
    state: present

- name: Set Password Expiration Days
  lineinfile:
    dest: '/etc/login.defs'
    regexp: "PASS_MIN_DAYS"
    line: "PASS_MIN_DAYS 7"
    state: present

- name: Set Default umask for Users
  lineinfile:
    dest: '/etc/login.defs'
    regexp: "UMASK"
    line: "UMASK 077"
    state: present
