---
# Include Variables Files
#******************************************************************************
- name: Include Variables
  include_vars: "vars.yml"

# Include the individual tasks files
#******************************************************************************

- include: "secure_boot.yml"
- include: "ssh_settings.yml"
- include: "configure_pam.yml"
- include: "account_settings.yml"
- include: "misc.yml"
- include: "ntp.yml"
- include: "cron.yml"
- include: "core_dumps.yml"
- include: "systemctl.yml"
- include: "kernel_modules.yml"
- include: "reboot.yml"